name: quiz_radioamatori
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  sentry_flutter: ^9.7.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.1
  talker_flutter: ^5.0.2
  equatable: ^2.0.5
  flutter_hooks: ^0.21.2
  flutter_svg: ^2.0.10+1
  hooks_riverpod: ^3.0.3
  uuid: ^4.3.3
  intl: any
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  supabase_flutter: ^2.5.4
  supabase_auth_ui: ^0.5.0
  auto_route: ^10.1.0+1
  gap: ^3.0.1
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  collection: ^1.18.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.1
  introduction_screen: ^4.0.0
  shared_preferences: ^2.3.2
  talker_dio_logger: ^5.0.2
  dio: ^5.7.0
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.0
  permission_handler: ^12.0.0+1
  social_auth_buttons: ^2.0.2
  sign_in_with_apple: ^6.1.4
  google_sign_in: ^6.3.0
  crypto: ^3.0.6
  share_plus: ^12.0.1
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  sentry_dart_plugin: ^3.1.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  freezed: ^3.0.6
  json_serializable: ^6.7.1
  very_good_analysis: ^10.0.0
  auto_route_generator: ^10.2.3
  flutter_launcher_icons: "^0.14.1"
  build_runner: ^2.4.13
  
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/icon/

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: quiz_radioamatori
  org: auroradigital
